/* tslint:disable */
/* eslint-disable */
/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


export * from './api/answers-api';
export * from './api/audio-api';
export * from './api/chat-api';
export * from './api/classifications-api';
export * from './api/completions-api';
export * from './api/edits-api';
export * from './api/embeddings-api';
export * from './api/engines-api';
export * from './api/files-api';
export * from './api/finetunes-api';
export * from './api/images-api';
export * from './api/models-api';
export * from './api/moderations-api';

