/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  AnswersApi,
  AudioApi,
  ChatApi,
  ClassificationsApi,
  CompletionsApi,
  EditsApi,
  EmbeddingsApi,
  EnginesApi,
  FilesApi,
  FinetunesApi,
  ImagesApi,
  ModelsApi,
  ModerationsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";

export class Openai {
  readonly answers: AnswersApi;
  readonly audio: AudioApi;
  readonly chat: ChatApi;
  readonly classifications: ClassificationsApi;
  readonly completions: CompletionsApi;
  readonly edits: EditsApi;
  readonly embeddings: EmbeddingsApi;
  readonly engines: EnginesApi;
  readonly files: FilesApi;
  readonly finetunes: FinetunesApi;
  readonly images: ImagesApi;
  readonly models: ModelsApi;
  readonly moderations: ModerationsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    const configuration = new Configuration(configurationParameters);
    this.answers = new AnswersApi(configuration);
    this.audio = new AudioApi(configuration);
    this.chat = new ChatApi(configuration);
    this.classifications = new ClassificationsApi(configuration);
    this.completions = new CompletionsApi(configuration);
    this.edits = new EditsApi(configuration);
    this.embeddings = new EmbeddingsApi(configuration);
    this.engines = new EnginesApi(configuration);
    this.files = new FilesApi(configuration);
    this.finetunes = new FinetunesApi(configuration);
    this.images = new ImagesApi(configuration);
    this.models = new ModelsApi(configuration);
    this.moderations = new ModerationsApi(configuration);
  }

}
