/* tslint:disable */
/* eslint-disable */
/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CreateTranslationRequest
 */
export interface CreateTranslationRequest {
    /**
     * The audio file to translate, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm. 
     * @type {File}
     * @memberof CreateTranslationRequest
     */
    'file': File;
    /**
     * ID of the model to use. Only `whisper-1` is currently available. 
     * @type {string}
     * @memberof CreateTranslationRequest
     */
    'model': string;
    /**
     * An optional text to guide the model\'s style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should be in English. 
     * @type {string}
     * @memberof CreateTranslationRequest
     */
    'prompt'?: string;
    /**
     * The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt. 
     * @type {string}
     * @memberof CreateTranslationRequest
     */
    'response_format'?: string;
    /**
     * The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit. 
     * @type {number}
     * @memberof CreateTranslationRequest
     */
    'temperature'?: number;
}

